# network
batch: 3
epoch: 100
bilstm_layers: 1 
word_dim: 200
conference_dim: 10
entity_type_dim: 10
out_dim: 100
type_dim: 10
dist_dim: 10
drop_rate: 0.3
drop_node: 0.5
drop_o: 0.3
drop_i: 0.5
beta: 0.8
walks_iter: 3
opt: adam
lr: 0.001
gc: 10
reg: 0.0001
patience: 10

# data based
train_data: ../data/CDR/processed/train+dev_filter.data
test_data: ../data/CDR/processed/test_filter.data
embeds: ../embeds/PubMed-CDR.txt
folder: ../results/cdr/dd
save_pred: test

# options (chosen m parse input otherwise false)
lowercase: false
plot: true
show_class: false
param_avg: true
early_stop: false
save_model: true
types: true
dist: true
conference: true
entity_type: true
gcn: false
gat: false
dggcn: false
dggat: true
multi_gcn: false
multi_gat: false
sent: mean # max p-means att
activate: sigmoid # glu gtu tanh relu sigmoid
single: false

# extra
seed: 0
shuffle_data: true
label2ignore: 1:NR:2
primary_metric: micro_f
direction: l2r+r2l
include_pairs: ['Chemical-Disease', 'Chemical-Chemical', 'Disease-Disease', 'Disease-Chemical']
classify_pairs: ['Chemical-Disease']
edges: ['MM', 'ME', 'MS', 'ES', 'SS-ind']
